/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gdsoftworks_androidapp_Bytes */

#ifndef _Included_com_gdsoftworks_androidapp_Bytes
#define _Included_com_gdsoftworks_androidapp_Bytes
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gdsoftworks_androidapp_Bytes
 * Method:    copyTo
 * Signature: (Ljava/nio/ByteBuffer;[FII)V
 */
JNIEXPORT void JNICALL Java_com_gdsoftworks_androidapp_Bytes_copyTo__Ljava_nio_ByteBuffer_2_3FII
  (JNIEnv *, jclass, jobject, jfloatArray, jint, jint);

/*
 * Class:     com_gdsoftworks_androidapp_Bytes
 * Method:    copyTo
 * Signature: (Ljava/nio/ShortBuffer;[SII)V
 */
JNIEXPORT void JNICALL Java_com_gdsoftworks_androidapp_Bytes_copyTo__Ljava_nio_ShortBuffer_2_3SII
  (JNIEnv *, jclass, jobject, jshortArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
